### ISSUE TITLE
Custom script variables cannot be used on larger channels

### ISSUE THREAD

**Issue by Azenet** [sogebot/sogeBot#4910]
Hi,

Whenever a custom script variable that contains a reference to users is run, runScript seems to be loading the whole user database ([here](https://github.com/sogebot/sogeBot/blob/f12ca712ea1886b6c699594e666bc8e2e44631cc/src/helpers/customvariables/runScript.ts#L54)). This makes this feature unusable in case the bot is tracking many users, which is usually the case on larger channels. It looks like the same thing can happen in the evaluate filter.

Thank you

**Comment by sogehige** [comment]
Will check thanks, we should probably get random user directly instead of just loading whole db
