### ISSUE TITLE
Creating a new alerts overlay, registry doesn't save.

### ISSUE THREAD

**Issue by reznyt** [sogebot/sogeBot#5138]
### Expected behavior
When saving a new alerts registry overlay, the selected registry should be saved.

### Actual behavior
When saving a new alerts registry overlay, the selected registry is not saved.

### Steps to reproduce
Create an alert registry
Create a new Group overlay
Add an Alerts Registry overlay
Select an Alert Registry to use in the overlay.
Save.

### Additional informations
Functionality appears to be broken by release 14.26.0. Briefly rolling back to 14.25.0, updating the overlay, saving and rolling forward again is the suboptimal workaround I used.

First priority errors are thrown in the js console on selecting the alert registry box, referencing ctx not set.
Second priority errors are thrown in the overlay itself, referencing the fact a required ID variable is not set (reasoning, because of above)

**Comment by sogehige** [comment]
Will check thanks

**Comment by sogehige** [comment]
Fixed in ui-admin 45.1.8. Bot should update automatically or you can manually update through UI -> settings -> modules -> updated
